db.url=jdbc:sqlserver://DESKTOP-6VQK38J:1433;instanceName=SQL2025;databaseName=fabricadequeso;trustServerCertificate=true;encrypt=false;integratedSecurity=false;
db.user=janciel
db.password=1234
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
